### ISSUE TITLE
Need matching interface on RTP receiver.

### ISSUE THREAD

**Issue by steely-glint** [alvestrand/hackathon-encoded-media#1]
We have a similar abstraction layer in |pipe| - one common operation is fan-out where we take the encoded frames from an RTPReceiver and feed them into _multiple_ RTPSenders. 

So I would recommend a matching interface on RTP Receiver that allows such piping to take place. 
I suppose this could be shimmed on your API with a dummy RTPSender that sends nothing and Diverts everything to multiple other senders  - but that seems ugly.

**Comment by alvestrand** [comment]
Yep, that's the plan. I just hadn't written it in yet.
This should work:

framesource = pc1.getReceivers()[n].divertFrames();
for pc = pc2 ... pcn {
   framesink[n] = pc.insertFrames(relay);
}

framesource.stream.reader = function(frame) {

for (pc in pc2...pcn) {
  framesink[i].stream.write(adjustMetadata(frame.clone()))
}

this syntax is completely bogus, which is why I want to play with what the shim should look like.
I think we both need to clone the frame before sending it out and potentially adjust the metadata on a per-receiver basis, which is why I'm not suggesting that we support "for sender in sender2..sender1 { receiver.connectTo(sender); }" (a producer generates one frame, and the processor has to take a conscious decision to clone it for multiple sinks).
